import Apple from "/Apple.png";
import BigApple from "/BigApple.png";
import SliderImage1 from "/SliderImage1.png";
import SliderImage2 from "/SliderImage2.png";
import SliderImage3 from "/SliderImage3.png";
import BigCabbage from "/BigCabbage.png";

export const products = [
  {
    id: "product-001",
    title: "Green Apple",
    price: 15,
    image: Apple,
    averageRating: 4,
    ratingCount: 100,
    inStock: true,
    images: [Apple, BigApple, SliderImage1, SliderImage2, SliderImage3],
    description: "Fresh and crisp green apples rich in fiber and antioxidants.",
    discount: {
      isActive: true,
      percentage: 10,
      price: 15 - (15 * 10 / 100),
    },
    unit: "kg",
    tags: ["Fruits", "Healthy", "Organic", "Apple"],
    category: "Fruits",
    categoryId: "1",
  },
  {
    id: "product-002",
    title: "Red Cabbage",
    price: 12,
    image: BigApple,
    averageRating: 4.5,
    ratingCount: 85,
    inStock: true,
    images: [BigApple, Apple, SliderImage1],
    description: "Crunchy and colorful red cabbage, perfect for salads.",
    discount: {
      isActive: false,
      percentage: 0,
      price: 12,
    },
    unit: "kg",
    tags: ["Vegetables", "Cabbage", "Fiber", "Healthy"],
    category: "Vegetables",
    categoryId: "1",
  },
  {
    id: "product-003",
    title: "Banana",
    price: 10,
    image: SliderImage1,
    averageRating: 4.2,
    ratingCount: 110,
    inStock: true,
    images: [SliderImage1, Apple, SliderImage3],
    description: "Sweet and ripe bananas, a great source of energy.",
    discount: {
      isActive: true,
      percentage: 5,
      price: 10 - (10 * 5 / 100),
    },
    unit: "kg",
    tags: ["Fruits", "Energy", "Healthy", "Snack"],
    category: "Fruits",
    categoryId: "1",
  },
  {
    id: "product-004",
    title: "Carrot",
    price: 8,
    image: SliderImage2,
    averageRating: 4,
    ratingCount: 70,
    inStock: true,
    images: [SliderImage2, Apple, SliderImage1],
    description: "Crunchy carrots rich in vitamin A and beta-carotene.",
    discount: {
      isActive: false,
      percentage: 0,
      price: 8,
    },
    unit: "kg",
    tags: ["Vegetables", "Orange", "Healthy", "Root"],
    category: "Vegetables",
    categoryId: "1",
  },
  {
    id: "product-005",
    title: "Tomato",
    price: 9,
    image: SliderImage3,
    averageRating: 4.3,
    ratingCount: 90,
    inStock: true,
    images: [SliderImage3, SliderImage1, SliderImage2],
    description: "Juicy tomatoes great for sauces and salads.",
    discount: {
      isActive: true,
      percentage: 15,
      price: 9 - (9 * 15 / 100),
    },
    unit: "kg",
    tags: ["Vegetables", "Juicy", "Red", "Fresh"],
    category: "Vegetables",
    categoryId: "1",
  },
  {
    id: "product-006",
    title: "Orange",
    price: 14,
    image: Apple,
    averageRating: 4.6,
    ratingCount: 150,
    inStock: true,
    images: [Apple, SliderImage3, SliderImage2],
    description: "Citrus oranges packed with vitamin C.",
    discount: {
      isActive: true,
      percentage: 20,
      price: 14 - (14 * 20 / 100),
    },
    unit: "kg",
    tags: ["Fruits", "Citrus", "Orange", "Healthy"],
    category: "Fruits",
    categoryId: "1",
  },
  {
    id: "product-007",
    title: "Broccoli",
    price: 13,
    image: BigApple,
    averageRating: 4.4,
    ratingCount: 95,
    inStock: false,
    images: [BigApple, SliderImage2, SliderImage1],
    description: "Fresh green broccoli, a powerhouse of nutrients.",
    discount: {
      isActive: false,
      percentage: 0,
      price: 13,
    },
    unit: "kg",
    tags: ["Vegetables", "Green", "Healthy", "Fiber"],
    category: "Vegetables",
    categoryId: "1",
  },
  {
    id: "product-008",
    title: "Lettuce",
    price: 7,
    image: SliderImage1,
    averageRating: 3.9,
    ratingCount: 60,
    inStock: true,
    images: [SliderImage1, SliderImage2],
    description: "Fresh lettuce leaves, perfect for wraps and burgers.",
    discount: {
      isActive: false,
      percentage: 0,
      price: 7,
    },
    unit: "kg",
    tags: ["Vegetables", "Leafy", "Salad", "Fresh"],
    category: "Vegetables",
    categoryId: "1",
  },
  {
    id: "product-009",
    title: "Strawberry",
    price: 18,
    image: SliderImage2,
    averageRating: 4.8,
    ratingCount: 130,
    inStock: true,
    images: [SliderImage2, SliderImage3, Apple],
    description: "Sweet strawberries rich in antioxidants.",
    discount: {
      isActive: true,
      percentage: 10,
      price: 18 - (18 * 10 / 100),
    },
    unit: "kg",
    tags: ["Fruits", "Red", "Berry", "Sweet"],
    category: "Fruits",
    categoryId: "1",
  },
  {
    id: "product-010",
    title: "Zucchini",
    price: 11,
    image: SliderImage3,
    averageRating: 4.1,
    ratingCount: 50,
    inStock: false,
    images: [SliderImage3, Apple, SliderImage1],
    description: "Fresh zucchini, ideal for grilling or baking.",
    discount: {
      isActive: false,
      percentage: 0,
      price: 11,
    },
    unit: "kg",
    tags: ["Vegetables", "Green", "Squash", "Fresh"],
    category: "Vegetables",
    categoryId: "1",
  },
];

export const bigProduct = {
  id: Math.random(),
  title: "Big Apples",
  image: BigApple,
  price: 24,
  discount: 50,
  averageRating: 4,
  ratingCount: 100,
  inStock: true,
  unit: "kg",
};

export const modalProduct = {
  id: Math.random(),
  title: "Big Apples",
  images: [BigCabbage, SliderImage1, SliderImage2, SliderImage3],
  price: 24,
  discount: 12,
  discountedPrice: 24 - (24 * 12 / 100),
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  averageRating: 4,
  ratingCount: 100,
  unit: "kg",
  category: "Vegetables",
  tags: ["Vegetables", "Healthy", "Chinese Cabbage", "Green Cabbage"],
}